/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataExecution } from './mlMetadataExecution';

export class ApiListExecutionsResponse {
    'executions'?: Array<MlMetadataExecution>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "executions",
            "baseName": "executions",
            "type": "Array<MlMetadataExecution>"
        }    ];

    static getAttributeTypeMap() {
        return ApiListExecutionsResponse.attributeTypeMap;
    }
}

