/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataExecutionType } from './mlMetadataExecutionType';

export class ApiListExecutionTypesResponse {
    'executionTypes'?: Array<MlMetadataExecutionType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "executionTypes",
            "baseName": "execution_types",
            "type": "Array<MlMetadataExecutionType>"
        }    ];

    static getAttributeTypeMap() {
        return ApiListExecutionTypesResponse.attributeTypeMap;
    }
}

