/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactType } from './mlMetadataArtifactType';

export class ApiListArtifactTypesResponse {
    'artifactTypes'?: Array<MlMetadataArtifactType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "artifactTypes",
            "baseName": "artifact_types",
            "type": "Array<MlMetadataArtifactType>"
        }    ];

    static getAttributeTypeMap() {
        return ApiListArtifactTypesResponse.attributeTypeMap;
    }
}

