/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactStructType } from './mlMetadataArtifactStructType';

export class MlMetadataDictArtifactStructType {
    /**
    * Underlying properties for the type.
    */
    'properties'?: { [key: string]: MlMetadataArtifactStructType; };
    /**
    * If true, then if properties[\"foo\"] can be None, then that key is not required.
    */
    'noneTypeNotRequired'?: boolean;
    'extraPropertiesType'?: MlMetadataArtifactStructType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: MlMetadataArtifactStructType; }"
        },
        {
            "name": "noneTypeNotRequired",
            "baseName": "none_type_not_required",
            "type": "boolean"
        },
        {
            "name": "extraPropertiesType",
            "baseName": "extra_properties_type",
            "type": "MlMetadataArtifactStructType"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataDictArtifactStructType.attributeTypeMap;
    }
}

