/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactStructType } from './mlMetadataArtifactStructType';
import { MlMetadataPropertyType } from './mlMetadataPropertyType';

export class MlMetadataExecutionType {
    /**
    * The id of the type. 1-1 relationship between type names and IDs.
    */
    'id'?: string;
    /**
    * The name of the type.
    */
    'name'?: string;
    /**
    * The schema of the type. Properties are always optional in the execution.
    */
    'properties'?: { [key: string]: MlMetadataPropertyType; };
    'inputType'?: MlMetadataArtifactStructType;
    'outputType'?: MlMetadataArtifactStructType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: MlMetadataPropertyType; }"
        },
        {
            "name": "inputType",
            "baseName": "input_type",
            "type": "MlMetadataArtifactStructType"
        },
        {
            "name": "outputType",
            "baseName": "output_type",
            "type": "MlMetadataArtifactStructType"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataExecutionType.attributeTypeMap;
    }
}

