/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactType } from './mlMetadataArtifactType';
import { MlMetadataDictArtifactStructType } from './mlMetadataDictArtifactStructType';
import { MlMetadataIntersectionArtifactStructType } from './mlMetadataIntersectionArtifactStructType';
import { MlMetadataListArtifactStructType } from './mlMetadataListArtifactStructType';
import { MlMetadataTupleArtifactStructType } from './mlMetadataTupleArtifactStructType';
import { MlMetadataUnionArtifactStructType } from './mlMetadataUnionArtifactStructType';

/**
* The type of an ArtifactStruct. An artifact struct type represents an infinite set of artifact structs. It can specify the input or output type of an ExecutionType. See the more specific types referenced in the message for more details.
*/
export class MlMetadataArtifactStructType {
    'simple'?: MlMetadataArtifactType;
    'unionType'?: MlMetadataUnionArtifactStructType;
    'intersection'?: MlMetadataIntersectionArtifactStructType;
    'list'?: MlMetadataListArtifactStructType;
    'none'?: object;
    /**
    * Every ArtifactStruct is a member of this type.
    */
    'any'?: object;
    'tuple'?: MlMetadataTupleArtifactStructType;
    'dict'?: MlMetadataDictArtifactStructType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "simple",
            "baseName": "simple",
            "type": "MlMetadataArtifactType"
        },
        {
            "name": "unionType",
            "baseName": "union_type",
            "type": "MlMetadataUnionArtifactStructType"
        },
        {
            "name": "intersection",
            "baseName": "intersection",
            "type": "MlMetadataIntersectionArtifactStructType"
        },
        {
            "name": "list",
            "baseName": "list",
            "type": "MlMetadataListArtifactStructType"
        },
        {
            "name": "none",
            "baseName": "none",
            "type": "object"
        },
        {
            "name": "any",
            "baseName": "any",
            "type": "object"
        },
        {
            "name": "tuple",
            "baseName": "tuple",
            "type": "MlMetadataTupleArtifactStructType"
        },
        {
            "name": "dict",
            "baseName": "dict",
            "type": "MlMetadataDictArtifactStructType"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataArtifactStructType.attributeTypeMap;
    }
}

