/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataValue } from './mlMetadataValue';

export class MlMetadataArtifact {
    /**
    * The id of the artifact.
    */
    'id'?: string;
    /**
    * The id of an ArtifactType. Type must be specified when an artifact is created, and it cannot be changed.
    */
    'typeId'?: string;
    /**
    * The uniform resource identifier of the physical artifact. May be empty if there is no physical artifact.
    */
    'uri'?: string;
    /**
    * Properties of the artifact. Properties must be specified in the ArtifactType.
    */
    'properties'?: { [key: string]: MlMetadataValue; };
    /**
    * User provided custom properties which are not defined by its type.
    */
    'customProperties'?: { [key: string]: MlMetadataValue; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "typeId",
            "baseName": "type_id",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: MlMetadataValue; }"
        },
        {
            "name": "customProperties",
            "baseName": "custom_properties",
            "type": "{ [key: string]: MlMetadataValue; }"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataArtifact.attributeTypeMap;
    }
}

