/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactStructType } from './mlMetadataArtifactStructType';

/**
* Represents an ArtifactStruct list type with homogeneous elements.
*/
export class MlMetadataListArtifactStructType {
    'element'?: MlMetadataArtifactStructType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "element",
            "baseName": "element",
            "type": "MlMetadataArtifactStructType"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataListArtifactStructType.attributeTypeMap;
    }
}

