/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataPropertyType } from './mlMetadataPropertyType';

export class MlMetadataArtifactType {
    /**
    * The id of the type. 1-1 relationship between type names and IDs.
    */
    'id'?: string;
    /**
    * The name of the type.
    */
    'name'?: string;
    /**
    * The schema of the type. Properties are always optional in the artifact. Properties of an artifact type can be expanded but not contracted (i.e., you can add columns but not remove them).
    */
    'properties'?: { [key: string]: MlMetadataPropertyType; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: MlMetadataPropertyType; }"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataArtifactType.attributeTypeMap;
    }
}

