/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactStructType } from './mlMetadataArtifactStructType';

/**
* An ordered list of heterogenous artifact structs. The length of the list is fixed. Each position in the list can have a different type.
*/
export class MlMetadataTupleArtifactStructType {
    'elements'?: Array<MlMetadataArtifactStructType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "elements",
            "baseName": "elements",
            "type": "Array<MlMetadataArtifactStructType>"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataTupleArtifactStructType.attributeTypeMap;
    }
}

