/**
 * api/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MlMetadataArtifactStructType } from './mlMetadataArtifactStructType';

/**
* Represents a union of types.
*/
export class MlMetadataUnionArtifactStructType {
    /**
    * An artifact struct matches this type if it matches any of the candidates. If candidates is empty, this is a bottom type (matches no artifacts).
    */
    'candidates'?: Array<MlMetadataArtifactStructType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "candidates",
            "baseName": "candidates",
            "type": "Array<MlMetadataArtifactStructType>"
        }    ];

    static getAttributeTypeMap() {
        return MlMetadataUnionArtifactStructType.attributeTypeMap;
    }
}

