// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resource struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResourceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourceRequest) Reset()         { *m = GetResourceRequest{} }
func (m *GetResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetResourceRequest) ProtoMessage()    {}
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *GetResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceRequest.Unmarshal(m, b)
}
func (m *GetResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceRequest.Merge(m, src)
}
func (m *GetResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetResourceRequest.Size(m)
}
func (m *GetResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceRequest proto.InternalMessageInfo

func (m *GetResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Type struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type CreateTypeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema               []byte   `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTypeRequest) Reset()         { *m = CreateTypeRequest{} }
func (m *CreateTypeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTypeRequest) ProtoMessage()    {}
func (*CreateTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *CreateTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTypeRequest.Unmarshal(m, b)
}
func (m *CreateTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTypeRequest.Marshal(b, m, deterministic)
}
func (m *CreateTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTypeRequest.Merge(m, src)
}
func (m *CreateTypeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTypeRequest.Size(m)
}
func (m *CreateTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTypeRequest proto.InternalMessageInfo

func (m *CreateTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTypeRequest) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

func init() {
	proto.RegisterType((*Resource)(nil), "api.Resource")
	proto.RegisterType((*GetResourceRequest)(nil), "api.GetResourceRequest")
	proto.RegisterType((*Type)(nil), "api.Type")
	proto.RegisterType((*CreateTypeRequest)(nil), "api.CreateTypeRequest")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0x3b, 0x31,
	0x14, 0xc5, 0x99, 0x69, 0x29, 0xff, 0xde, 0xbf, 0x55, 0xcc, 0xa2, 0xad, 0x83, 0xa8, 0x64, 0x55,
	0xba, 0x68, 0xd0, 0xee, 0x84, 0x22, 0xd8, 0x85, 0x2b, 0x37, 0xa3, 0xb8, 0xbf, 0xce, 0x5c, 0x6a,
	0xd0, 0x4e, 0x62, 0x92, 0x0e, 0x14, 0xe9, 0xc6, 0x57, 0xf0, 0xd1, 0x7c, 0x00, 0x37, 0x3e, 0x88,
	0x24, 0xce, 0xd8, 0x42, 0xc5, 0xcd, 0x7c, 0x9c, 0x73, 0xf2, 0xcb, 0xfd, 0x80, 0x0e, 0x6a, 0x29,
	0x50, 0xcb, 0x91, 0x36, 0xca, 0x29, 0xd6, 0x40, 0x2d, 0x93, 0xc3, 0x99, 0x52, 0xb3, 0x27, 0x12,
	0xc1, 0x2a, 0x0a, 0xe5, 0xd0, 0x49, 0x55, 0xd8, 0xef, 0x08, 0x3f, 0x82, 0x7f, 0x29, 0x59, 0xb5,
	0x30, 0x19, 0x31, 0x06, 0xcd, 0x02, 0xe7, 0xd4, 0x8f, 0x4e, 0xa2, 0x41, 0x3b, 0x0d, 0xdf, 0x7c,
	0x00, 0xec, 0x8a, 0x5c, 0x1d, 0x49, 0xe9, 0x79, 0x41, 0xd6, 0xfd, 0x9a, 0xbc, 0x84, 0xe6, 0xed,
	0x52, 0x13, 0xdb, 0x85, 0x58, 0xe6, 0x95, 0x13, 0xcb, 0xfc, 0x27, 0x1b, 0xaf, 0xb3, 0xac, 0x0b,
	0x2d, 0x9b, 0x3d, 0xd0, 0x1c, 0xfb, 0x8d, 0xa0, 0x56, 0x7f, 0xfc, 0x02, 0xf6, 0xa7, 0x86, 0xd0,
	0x91, 0x27, 0xfd, 0x71, 0xd9, 0x06, 0xc0, 0x63, 0x77, 0x6a, 0xc0, 0xd9, 0x47, 0x04, 0x7b, 0xd7,
	0xe4, 0x30, 0x47, 0x87, 0x37, 0x64, 0x4a, 0x99, 0x11, 0xbb, 0x83, 0xff, 0x1b, 0x2d, 0xb0, 0xde,
	0xc8, 0x0f, 0x68, 0xbb, 0xa9, 0xa4, 0x13, 0x8c, 0x5a, 0xe5, 0xc7, 0xaf, 0xef, 0x9f, 0x6f, 0xf1,
	0x01, 0xeb, 0x85, 0xc9, 0x95, 0xa7, 0xc2, 0x54, 0x8e, 0x78, 0xf1, 0x25, 0xac, 0x98, 0x03, 0x58,
	0x17, 0xcb, 0xba, 0xe1, 0xf4, 0x56, 0xf5, 0x49, 0x3b, 0xe8, 0x5e, 0xe1, 0xd3, 0x40, 0x9c, 0xf0,
	0x71, 0x4d, 0x74, 0x4b, 0x5d, 0xd1, 0x26, 0xfe, 0x61, 0x35, 0x66, 0x64, 0xc5, 0x50, 0x3c, 0xca,
	0x22, 0xf7, 0xef, 0x92, 0x8c, 0xf5, 0xbb, 0x12, 0xc3, 0xd5, 0x79, 0xd5, 0xe1, 0x7d, 0x2b, 0xec,
	0x6d, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x2f, 0xe9, 0xc8, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*Type, error)
}

type metadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetadataServiceClient(cc *grpc.ClientConn) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/api.MetadataService/GetResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*Type, error) {
	out := new(Type)
	err := c.cc.Invoke(ctx, "/api.MetadataService/CreateType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	GetResource(context.Context, *GetResourceRequest) (*Resource, error)
	CreateType(context.Context, *CreateTypeRequest) (*Type, error)
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/CreateType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateType(ctx, req.(*CreateTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResource",
			Handler:    _MetadataService_GetResource_Handler,
		},
		{
			MethodName: "CreateType",
			Handler:    _MetadataService_CreateType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
